version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
  postgres:
    build:
      context: ./postgres
    restart: always
    env_file:
      ${PWD}/postgres/.env
    ports:
      - "5432:5432"
  api:
    build:
      dockerfile: Dockerfile-minimal-dev
      context: ./twin_api
    user: root
    environment:
      - CHOWN_EXTRA="/home/dpsim"
      - CHOWN_EXTRA_OPTS="-R"
    ports:
      # expose API on port 31032
      - "5050:5050"
    volumes:
      # mount credentials file
      - ${PWD}/credentials/:/home/dpsim/credentials/
      - ${PWD}/credentials/credentials.json:/home/dpsim/credentials/credentials.json
      # mount network models for dpsim
      - ${PWD}/network_model/:/home/dpsim/network_model/
      # during development, mount volumes from host machine into docker container
      - ${PWD}/twin_api/api:/home/dpsim/twin_api/api
    env_file:
      ${PWD}/postgres/.env
  frontend:
    build:
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
      context: ./twin_frontend
    volumes:
    #  # don't try to overwrite node_modules folder inside container, leave it as is
      - /app/node_modules
    #  # mount the contents of the twin_frontend directory into the '/app' folder of the container
    #  # any changes made in this directory will the cause the react development server to rebuild the app
      - ./twin_frontend:/app