version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3003:80"
    depends_on:
      - frontend
      - api
  api:
    build:
      dockerfile: Dockerfile_mini
      context: ./twin_api
    user: root
    #environment:
    #  - CHOWN_EXTRA="/home/jovyan"
    #  - CHOWN_EXTRA_OPTS="-R"
    #ports:
      # expose API on port 31032
    #  - "31032:5050"
    volumes:
      # mount credentials file
      - ${PWD}/credentials/:/app/credentials/
      - ${PWD}/credentials/credentials.json:/app/credentials/credentials.json
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./twin_frontend