version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3003:80"
    depends_on:
      - frontend
      - api
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3001:3000'
  api:
    build:
      dockerfile: Dockerfile-api-dpsim.dev
      context: ./twin_api
    user: root
    environment:
      - CHOWN_EXTRA="/home/jovyan"
      - CHOWN_EXTRA_OPTS="-R"
    ports:
      # expose API on port 31032
      - "31032:5050"
    volumes:
      # mount credentials file
      - ${PWD}/credentials/:/home/jovyan/credentials/
      - ${PWD}/credentials/credentials.json:/home/jovyan/credentials/credentials.json
      # mount network models for dpsim
      - ${PWD}/network_model/:/home/jovyan/network_model/
      # during development, mount volumes from host machine into docker container
      #- ./twin_api:/home/jovyan/twin_api
  frontend:
    build:
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
      context: ./twin_frontend
    volumes:
    #  # don't try to overwrite node_modules folder inside container, leave it as is
      - /app/node_modules
    #  # mount the contents of the twin_frontend directory into the '/app' folder of the container
    #  # any changes made in this directory will the cause the react development server to rebuild the app
      - ./twin_frontend:/app