# Specify parent image. Please select a fixed tag here.
ARG BASE_IMAGE=jupyter/minimal-notebook:python-3.10
FROM ${BASE_IMAGE}

# Install toolchain to build dpsim
USER root
ADD install-dev-tools.sh .
RUN ./install-dev-tools.sh

# Install packages via requirements-api-dpsim.txt
ADD ./twin_api/requirements-api-dpsim.txt .
RUN pip install -r requirements-api-dpsim.txt

USER ${NB_USER}
WORKDIR /home/${NB_USER}

RUN git clone https://github.com/I-NERGY/Twin4DER.git

WORKDIR /home/${NB_USER}/twin_api 
ENTRYPOINT uvicorn main:app --reload --host 0.0.0.0 --port 5050