# compose file for building and running the API only
version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api-dpsim.dev
    user: root
    environment:
      - CHOWN_EXTRA="/home/jovyan"
      - CHOWN_EXTRA_OPTS="-R"
    ports:
      # expose API on port 31032
      - "31032:5050"
      # expose Jupyter on port 8889
      - "8889:8888"
    # during development, mount volumes from host machine into docker container
    volumes:
      - .:/home/jovyan/twin_api
