# use python base image
FROM python:3.9.18-alpine

# set the working directory in the container
WORKDIR /app

# copy the requirements file into the container
COPY requirements-api.txt .

# nstall the Python dependencies
RUN pip install -r requirements-api.txt

# Copy the entire current directory into the container
COPY . .

# expose the port the Flask app runs on
# EXPOSE 31032

# Define the command to run the Flask app
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]