# SPDX-FileCopyrightText: 2023, Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

# compose file for building and running the API only
version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api-dpsim.dev
    user: root
    environment:
      - CHOWN_EXTRA="/home/jovyan"
      - CHOWN_EXTRA_OPTS="-R"
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/twin_api:/home/jovyan/twin_api
      - ${PWD}/network_model:/home/jovyan/network_model
