# SPDX-FileCopyrightText: 2023, Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

# compose file for building and running the API only
version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-minimal-dev
    user: root
    environment:
      - CHOWN_EXTRA="/home/dpsim"
      - CHOWN_EXTRA_OPTS="-R"
    ports:
      - "5050:5050"
    volumes:
      - ../credentials:/home/dpsim/credentials
      - ${PWD}/twin_api/api:/home/dpsim/twin_api/api
      - ${PWD}/network_model:/home/dpsim/network_model
