FROM jupyter/minimal-notebook:python-3.10

# Install toolchain to build dpsim
USER root
ADD install-dev-tools.sh .
RUN ./install-dev-tools.sh

# Dependency for PostgresDB access, needed before installing psycopg2 python package
RUN apt-get update && apt-get install -y libpq-dev

# Install packages via requirements-api-dpsim.txt
ADD requirements-api-dpsim.txt .
RUN pip install -r requirements-api-dpsim.txt

USER ${NB_USER}
WORKDIR /home/${NB_USER}/twin_api 

# Copy the entire current directory into the container
COPY . .

ENTRYPOINT uvicorn main:app --reload --host 0.0.0.0 --port 5050