name: Run API Tests

on:
  push:
    branches:
      - add_tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Build and run API container
      run: docker compose -f ${PWD}/twin_api/docker-compose.yml up -d

    - name: Wait for API container to start
      run: sleep 10

    - name: Upgrade pip
      run: pip3 install --upgrade pip

    - name: Install dependencies for tests
      run: pip3 install -r twin_api/tests/requirements.txt -r twin_api/requirements-api-dpsim-min.txt

    - name: Run tests
      run: pytest

    - name: Stop API container
      run: docker compose -f ${PWD}/twin_api/docker-compose.yml down